package org.canalesCMAC.domain.model;

public enum Institucion {
    ELSE,
    ELECTRO_UCAYALI,
    SEAL,
    CLARO,
    MUNICIPALIDAD_CUSCO,
    PAYTOPERU,
    UNIVCUSCO,
    YAGANASTE,
    WESTER_UNION,
    UNIVCONTINENTAL_UNIVERSIDAD,
    UNIVCONTINENTAL_CIDIOMAS
}