quarkus.http.port=8080
quarkus.application.name=chn-base-backend

recaudacion.electrosureste.url=https://appsrvdev.else.com.pe/wApiCobranzaLinea/SCobranza.svc
recaudacion.electrosureste.usuario=usuarioentidadfinan
recaudacion.electrosureste.clave=124@abc
recaudacion.electrosureste.soap.namespace=http://tempuri.org/

recaudacion.electroucayali.url=https://servicios.electroucayali.com.pe/WSFinancieraApiElectro
recaudacion.electroucayali.usuario=user
recaudacion.electroucayali.clave=password
recaudacion.electroucayali.codempresa=05

# SEAL (ISO8583)
recaudacion.seal.url=http://localhost:8080/seal
recaudacion.seal.usuario=INTERBA
recaudacion.seal.car=9999
recaudacion.seal.acquirer=40001000
recaudacion.seal.forward=20013005
recaudacion.seal.moneda=604
recaudacion.seal.agencia=015
recaudacion.seal.direccion=Av. Carlos Villaran 140 - La Victoria