quarkus.http.port=8080
quarkus.application.name=chn-base-backend

recaudacion.electrosureste.url=https://appsrvdev.else.com.pe/wApiCobranzaLinea/SCobranza.svc
recaudacion.electrosureste.usuario=usuarioentidadfinan
recaudacion.electrosureste.clave=124@abc
recaudacion.electrosureste.soap.namespace=http://tempuri.org/

recaudacion.electroucayali.url=https://servicios.electroucayali.com.pe/WSFinancieraApiElectro
recaudacion.electroucayali.usuario=user
recaudacion.electroucayali.clave=password
recaudacion.electroucayali.codempresa=05

# SEAL (ISO8583)
recaudacion.seal.url=http://localhost:8080/seal
recaudacion.seal.usuario=INTERBA
recaudacion.seal.car=9999
recaudacion.seal.acquirer=40001000
recaudacion.seal.forward=20013005
recaudacion.seal.moneda=604
recaudacion.seal.agencia=015
recaudacion.seal.direccion=Av. Carlos Villaran 140 - La Victoria


recaudacion.claro.url=http://localhost:8088/mockServiciosClaro
recaudacion.universidadcusco.url=http://localhost:8089/mockRecaudosSoapBinding
recaudacion.yaganaste.url=http://localhost:8090/mockSigmaService
recaudacion.municipalidadcusco.url=https://2647ca93-164c-44db-aa7f-0c4f997e5bb1.mock.pstmn.io/api/servicio/recuperar_orden_pago
recaudacion.paytoperu.url=http://desarrollo.paytoperu.com/cmac/consulta_pago